# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-23 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_pub_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
    ]
